// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintVault3D.Data;

#nullable disable

namespace PrintVault3D.Migrations
{
    [DbContext(typeof(PrintVaultDbContext))]
    [Migration("20260127200157_AddSourceFilePath")]
    partial class AddSourceFilePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PrintVault3D.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoKeywords")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default category for new models",
                            Name = "Uncategorized"
                        },
                        new
                        {
                            Id = 2,
                            AutoKeywords = "benchy,calibration,test,cube,temp,tower",
                            Description = "Calibration prints",
                            Name = "Calibration"
                        },
                        new
                        {
                            Id = 3,
                            AutoKeywords = "mount,bracket,holder,clip,hook,hinge,gear",
                            Description = "Functional and mechanical parts",
                            Name = "Functional Parts"
                        },
                        new
                        {
                            Id = 4,
                            AutoKeywords = "toy,game,figure,figurine,miniature,dice",
                            Description = "Toys, games, and figurines",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 5,
                            AutoKeywords = "vase,art,decoration,decor,ornament,statue,bust",
                            Description = "Decorative items and art pieces",
                            Name = "Art & Decoration"
                        },
                        new
                        {
                            Id = 6,
                            AutoKeywords = "tool,wrench,screwdriver,organizer,box,tray",
                            Description = "Tools and utility items",
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 7,
                            AutoKeywords = "case,enclosure,raspberry,arduino,esp32,stand,dock",
                            Description = "Electronics enclosures and mounts",
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("PrintVault3D.Models.Gcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BedTemp")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FilamentLength")
                        .HasColumnType("REAL");

                    b.Property<double?>("FilamentWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InfillPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LayerHeight")
                        .HasColumnType("REAL");

                    b.Property<int?>("LinkConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NozzleTemp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrintTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("ModelId");

                    b.ToTable("Gcodes");
                });

            modelBuilder.Entity("PrintVault3D.Models.Model3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThumbnailGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("PrintVault3D.Models.Gcode", b =>
                {
                    b.HasOne("PrintVault3D.Models.Model3D", "Model")
                        .WithMany("Gcodes")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Model");
                });

            modelBuilder.Entity("PrintVault3D.Models.Model3D", b =>
                {
                    b.HasOne("PrintVault3D.Models.Category", "Category")
                        .WithMany("Models")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrintVault3D.Models.Category", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("PrintVault3D.Models.Model3D", b =>
                {
                    b.Navigation("Gcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
